### ISSUE TITLE
Please post compiled PDFs online

### ISSUE THREAD

**Issue by iankronquist** [flynd/asmsheets#1]
These seem really nice, but I'd rather not figure out how to build them myself. Compiling someone else's tex can be a pain, unfortunately.

Can you please compile them as PDFs and commit them here, or link to where the compiled versions are hosted in the README and the project description? Thanks!

**Comment by flynd** [comment]
Actually, they are already available. If you check under Releases there are PDFs posted for all the sheets:
https://github.com/flynd/asmsheets/releases

However I did realize that the latest release was over a year old and there has been at least some updates since then so I'll take this ticket as a reminder to make a new release. Version 5 is now up with ARMv8.1 extentions and full floating point and SIMD instruction set for ARMv7.
